Repository sulsulProject/sulsul_Project, pull requests merged in 2023-03, with the labels that each got.

#4 고객센터
  sulsul_Project/src/main/java/com/sist/web/CustomerController.java
  sulsul_Project/src/main/java/com/sist/web/CustomerRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/customerservice/customerservice.jsp
Labels: 화면

#5 야호
  README.md
  sulsul_Project/src/main/webapp/WEB-INF/regular/regular.jsp
Labels: 설정

#7 고객센터 화면
  sulsul_Project/src/main/java/com/sist/web/CustomerController.java
  sulsul_Project/src/main/java/com/sist/web/CustomerRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/config/db.properties
  sulsul_Project/src/main/webapp/WEB-INF/main/header.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 화면

#8 regular.jsp 깃 수정
  sulsul_Project/src/main/java/com/sist/vo/RegularVO.java
  sulsul_Project/src/main/webapp/WEB-INF/regular/regular.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 버그

#9 고객센터
  sulsul_Project/src/main/java/com/sist/dao/FaqDAO.java
  sulsul_Project/src/main/java/com/sist/dao/InformationDAO.java
  sulsul_Project/src/main/java/com/sist/mapper/FaqMapper.java
  sulsul_Project/src/main/java/com/sist/mapper/InformationMapper.java
  sulsul_Project/src/main/java/com/sist/vo/AskVO.java
  sulsul_Project/src/main/java/com/sist/vo/FaqCategoryVO.java
  sulsul_Project/src/main/java/com/sist/vo/FaqVO.java
  sulsul_Project/src/main/java/com/sist/vo/InformationUseVO.java
  sulsul_Project/src/main/java/com/sist/vo/NationIntroduceVO.java
  sulsul_Project/src/main/java/com/sist/web/CustomerController.java
  sulsul_Project/src/main/webapp/WEB-INF/customer/customer_ask.jsp
  sulsul_Project/src/main/webapp/WEB-INF/customer/customer_faq.jsp
  sulsul_Project/src/main/webapp/WEB-INF/customer/customer_infomation.jsp
Labels: 화면

#10 푸쉬연습
  sulsul_Project/src/main/webapp/WEB-INF/trade/list.jsp
Labels: 질문

#14 로그인 기능 구현
  sulsul_Project/src/main/java/com/sist/dao/MemberDAO.java
  sulsul_Project/src/main/java/com/sist/mapper/MemberMapper.java
  sulsul_Project/src/main/java/com/sist/vo/MemberVO.java
  sulsul_Project/src/main/java/com/sist/web/MemberRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/main/header.jsp
  sulsul_Project/src/main/webapp/WEB-INF/member/login.jsp
  sulsul_Project/src/main/webapp/WEB-INF/member/signup.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 기능

#17 regular 기능추가
  sulsul_Project/src/main/java/com/sist/common/CommonException.java
  sulsul_Project/src/main/java/com/sist/dao/FaqDAO.java
  sulsul_Project/src/main/java/com/sist/dao/InformationDAO.java
  sulsul_Project/src/main/java/com/sist/dao/RegularDAO.java
  sulsul_Project/src/main/java/com/sist/dao/WineDAO.java
  sulsul_Project/src/main/java/com/sist/mapper/InformationMapper.java
  sulsul_Project/src/main/java/com/sist/mapper/RegularMapper.java
  sulsul_Project/src/main/java/com/sist/mapper/TradeMapper.java
  sulsul_Project/src/main/java/com/sist/mapper/WineMapper.java
  sulsul_Project/src/main/java/com/sist/vo/AskVO.java
  sulsul_Project/src/main/java/com/sist/vo/FaqCategoryVO.java
  sulsul_Project/src/main/java/com/sist/vo/FaqVO.java
  sulsul_Project/src/main/java/com/sist/vo/InformationUseVO.java
  sulsul_Project/src/main/java/com/sist/vo/NationIntroduceVO.java
  sulsul_Project/src/main/java/com/sist/vo/RegularBoardVO.java
  sulsul_Project/src/main/java/com/sist/vo/RegularVO.java
  sulsul_Project/src/main/java/com/sist/vo/TradeVO.java
  sulsul_Project/src/main/java/com/sist/web/CustomerController.java
  sulsul_Project/src/main/java/com/sist/web/CustomerRestController.java
  sulsul_Project/src/main/java/com/sist/web/MainController.java
  sulsul_Project/src/main/java/com/sist/web/NoticeController.java
  sulsul_Project/src/main/java/com/sist/web/RegularController.java
  sulsul_Project/src/main/java/com/sist/web/RegularRestController.java
  sulsul_Project/src/main/java/com/sist/web/TradeController.java
  sulsul_Project/src/main/java/com/sist/web/WineController.java
  sulsul_Project/src/main/java/com/sist/web/WineRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/config/application-context.xml
  sulsul_Project/src/main/webapp/WEB-INF/main/main.jsp
  sulsul_Project/src/main/webapp/WEB-INF/regular/detail.jsp
  sulsul_Project/src/main/webapp/WEB-INF/regular/detail2.jsp
  sulsul_Project/src/main/webapp/WEB-INF/regular/detail3.jsp
  sulsul_Project/src/main/webapp/WEB-INF/regular/insert.jsp
  sulsul_Project/src/main/webapp/WEB-INF/regular/regular.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 기능

#23 - 고객센터 화면 및 기능 수정
  sulsul_Project/src/main/java/com/sist/dao/FaqDAO.java
  sulsul_Project/src/main/java/com/sist/mapper/FaqMapper.java
  sulsul_Project/src/main/java/com/sist/web/CustomerController.java
  sulsul_Project/src/main/java/com/sist/web/CustomerRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/customer/ask_detail.jsp
  sulsul_Project/src/main/webapp/WEB-INF/customer/customer_faq.jsp
  sulsul_Project/src/main/webapp/WEB-INF/customer/faq_detail.jsp
  sulsul_Project/src/main/webapp/WEB-INF/main/header.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 기능, 화면

#25 -고객센터
  sulsul_Project/src/main/java/com/sist/web/AllReplyController.java
  sulsul_Project/src/main/java/com/sist/web/CustomerController.java
  sulsul_Project/src/main/java/com/sist/web/CustomerRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/customer/ask_detail.jsp
  sulsul_Project/src/main/webapp/WEB-INF/customer/customer_ask.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 기능, 화면

#27 feat:로그인+회원가입기능+CSS
  sulsul_Project/src/main/java/com/sist/dao/BoardDAO.java
  sulsul_Project/src/main/java/com/sist/dao/MemberDAO.java
  sulsul_Project/src/main/java/com/sist/mapper/MemberMapper.java
  sulsul_Project/src/main/java/com/sist/web/MainController.java
  sulsul_Project/src/main/java/com/sist/web/MemberController.java
  sulsul_Project/src/main/java/com/sist/web/MemberRestController.java
  sulsul_Project/src/main/webapp/WEB-INF/board/freeboard_detail.jsp
  sulsul_Project/src/main/webapp/WEB-INF/letter/recv_letter_list.jsp
  sulsul_Project/src/main/webapp/WEB-INF/main/footer.jsp
  sulsul_Project/src/main/webapp/WEB-INF/main/header.jsp
  sulsul_Project/src/main/webapp/WEB-INF/main/home.jsp
  sulsul_Project/src/main/webapp/WEB-INF/main/main.jsp
  sulsul_Project/src/main/webapp/WEB-INF/member/idfind.jsp
  sulsul_Project/src/main/webapp/WEB-INF/member/login.jsp
  sulsul_Project/src/main/webapp/WEB-INF/member/signup.jsp
  sulsul_Project/src/main/webapp/WEB-INF/trade/trade_list.jsp
  sulsul_Project/src/main/webapp/css/style.css
  sulsul_Project/src/main/webapp/images/delete.png
  sulsul_Project/src/main/webapp/images/list.png
  sulsul_Project/src/main/webapp/images/regular.jpg
  sulsul_Project/src/main/webapp/images/revise.png
  sulsul_Project/src/main/webapp/images/trade.jpg
  sulsul_Project/src/main/webapp/images/trash.png
  sulsul_Project/src/main/webapp/sul/chat/chat.jsp
  sulsul_Project/target/m2e-wtp/web-resources/META-INF/maven/com.sist/web/pom.properties
Labels: 기능, 화면
